version: "3"

services:
  db-xss:
    image: mysql:5.7
    ports:
      - '3310:3306'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
#      MYSQL_USER: 'root'
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      # MYSQL_HOST: ''
    networks:
      - openlxp
    
  app:
    # container_name: openlxp-xss
    build:
      context: .
    ports:
      - "8020:8010"
    command: >
      sh -c ". /tmp/app/start-app.sh"
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      SECRET_KEY_VAL: "${SECRET_KEY_VAL}"
      ENTITY_ID: "${ENTITY_ID}"
      SP_PUBLIC_CERT: "${SP_PUBLIC_CERT}"
      SP_PRIVATE_KEY: "${SP_PRIVATE_KEY}"
      # BAD_HOST: "${BAD_HOST}"
      # OVERIDE_HOST: "${OVERIDE_HOST}"
      # STRATEGY: "${STRATEGY}"
    volumes:
      - ./app:/tmp/app/openlxp-xss
      - ./nginx.default:/etc/nginx/conf.d/default.conf
    depends_on:
      - db-xss
    networks:
      - openlxp
  
  nginx:
    image: nginx:latest
    ports: 
      - 80:8020
    volumes: 
      - ./app:/tmp/app/openlxp-xss
      - ./nginx.default:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - openlxp
      
volumes:
  data01:
    driver: local
networks:
  openlxp:
    external: true
